<?php

$pays =[
    'Allemagne',
    'Albanie',
    'Andorre',
    'Arménie',
    'Autriche',
    'Azerbaïdjan',
    'Belgique',
    'Biélorussie',
    'Bosnie-Herzégovine',
    'Bulgarie',
    'Chypre',
    'Croatie',
    'Danemark',
    'Espagne',
    'Estonie',
    'Finlande',
    'France',
    'Géorgie',
    'Grèce',
    'Hongrie',
    'Irlande',
    'Islande',
    'Italie',
    'Lettonie',
    'Liechtenstein',
    'Lituanie',
    'Luxembourg',
    'République de Macédoine',
    'Malte',
    'Moldavie',
    'Monaco',
    'Monténégro',
    'Norvège',
    'Pays-Bas',
    'Pologne',
    'Portugal',
    'République tchèque',
    'Roumanie',
    'Royaume-Uni',
    'Russie',
    'Saint-Marin',
    'Serbie',
    'Slovaquie',
    'Slovénie',
    'Suède',
    'Suisse',
    'Ukraine',
    'Vatican'];
$rand = random_int(0,47);
echo $pays [$rand];